In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[45, 21],
       [14, 30],
       [46, 48],
       [ 9, 15],
       [23, 45],
       [12, 19],
       [70, 44],
       [78, 80],
       [90, 36],
       [42, 96]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [7]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.44444444, 0.07407407],
       [0.0617284 , 0.18518519],
       [0.45679012, 0.40740741],
       [0.        , 0.        ],
       [0.17283951, 0.37037037],
       [0.03703704, 0.04938272],
       [0.75308642, 0.35802469],
       [0.85185185, 0.80246914],
       [1.        , 0.25925926],
       [0.40740741, 1.        ]])

In [9]:
scaler_model.fit_transform(data)

array([[0.44444444, 0.07407407],
       [0.0617284 , 0.18518519],
       [0.45679012, 0.40740741],
       [0.        , 0.        ],
       [0.17283951, 0.37037037],
       [0.03703704, 0.04938272],
       [0.75308642, 0.35802469],
       [0.85185185, 0.80246914],
       [1.        , 0.25925926],
       [0.40740741, 1.        ]])

In [13]:
import pandas as pd

In [16]:
my_data = np.random.randint(0,101,(50,4))
my_data

array([[ 46,  80,  52,  57],
       [ 50,  35,  45,  31],
       [ 47,   8,  17,  54],
       [  1,  63,  28,  16],
       [ 41, 100,  80,   1],
       [ 29,  22,  22,  76],
       [ 34,  51,  13,   1],
       [ 21,  17,  93,  74],
       [ 82,   0,  38,  30],
       [  9,  36,  29,  63],
       [ 66,  29,  25,   2],
       [ 73,   4,  13,  98],
       [ 46,  60,  36,  13],
       [ 21,  58,  39,  84],
       [  1,  50,  24,  81],
       [ 15,   8,  16,  46],
       [ 77,   9,  51,  55],
       [ 35,  86,  77,  81],
       [ 75,  83,  50,  41],
       [ 91,  15,  97,   4],
       [ 66,  82,  76,  19],
       [  1,  82,  59,  53],
       [ 47,  61,  35,  49],
       [ 84,  17,  51,  25],
       [ 84,  64,  85,  61],
       [ 21,  30,  94,  26],
       [100,  56,  38,  78],
       [ 76,  77,   7,  88],
       [ 69,  12,  67,  17],
       [ 55,   6,  80,  55],
       [ 95,  38,  94,  35],
       [ 30,   9,  76,  49],
       [ 83,   2,  90,  34],
       [ 50,   8,  29,  95],
       [ 91,  

In [19]:
df = pd.DataFrame(data=my_data, columns=['f1','f2','f3','label'])

In [20]:
df

f1   f2  f3  label
0    46   80  52     57
1    50   35  45     31
2    47    8  17     54
3     1   63  28     16
4    41  100  80      1
5    29   22  22     76
6    34   51  13      1
7    21   17  93     74
8    82    0  38     30
9     9   36  29     63
10   66   29  25      2
11   73    4  13     98
12   46   60  36     13
13   21   58  39     84
14    1   50  24     81
15   15    8  16     46
16   77    9  51     55
17   35   86  77     81
18   75   83  50     41
19   91   15  97      4
20   66   82  76     19
21    1   82  59     53
22   47   61  35     49
23   84   17  51     25
24   84   64  85     61
25   21   30  94     26
26  100   56  38     78
27   76   77   7     88
28   69   12  67     17
29   55    6  80     55
30   95   38  94     35
31   30    9  76     49
32   83    2  90     34
33   50    8  29     95
34   91   57   3     32
35   26   48  54     30
36    2   87  37     55
37   65   61   2     89
38   84   91  30     21
39    6   52  19     21
40    8    7  99     93
41   57   88   9     56
42   25   50  19     58
43   50   82  47     39
44   54   52  10     43
45   83   18  44     53
46   98   32  91     93
47   85   86  41     74
48   56   91  34     84
49   99    0  48      9

In [21]:
X = df[['f1','f2','f3']]

In [22]:
X

f1   f2  f3
0    46   80  52
1    50   35  45
2    47    8  17
3     1   63  28
4    41  100  80
5    29   22  22
6    34   51  13
7    21   17  93
8    82    0  38
9     9   36  29
10   66   29  25
11   73    4  13
12   46   60  36
13   21   58  39
14    1   50  24
15   15    8  16
16   77    9  51
17   35   86  77
18   75   83  50
19   91   15  97
20   66   82  76
21    1   82  59
22   47   61  35
23   84   17  51
24   84   64  85
25   21   30  94
26  100   56  38
27   76   77   7
28   69   12  67
29   55    6  80
30   95   38  94
31   30    9  76
32   83    2  90
33   50    8  29
34   91   57   3
35   26   48  54
36    2   87  37
37   65   61   2
38   84   91  30
39    6   52  19
40    8    7  99
41   57   88   9
42   25   50  19
43   50   82  47
44   54   52  10
45   83   18  44
46   98   32  91
47   85   86  41
48   56   91  34
49   99    0  48

In [27]:
y = df['label']

In [28]:
y

0     57
1     31
2     54
3     16
4      1
5     76
6      1
7     74
8     30
9     63
10     2
11    98
12    13
13    84
14    81
15    46
16    55
17    81
18    41
19     4
20    19
21    53
22    49
23    25
24    61
25    26
26    78
27    88
28    17
29    55
30    35
31    49
32    34
33    95
34    32
35    30
36    55
37    89
38    21
39    21
40    93
41    56
42    58
43    39
44    43
45    53
46    93
47    74
48    84
49     9
Name: label, dtype: int32

In [25]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [33]:
X_train.shape

(35, 3)

In [34]:
X_test.shape

(15, 3)

In [35]:
X_train

f1  f2  f3
6   34  51  13
41  57  88   9
46  98  32  91
47  85  86  41
15  15   8  16
9    9  36  29
16  77   9  51
24  84  64  85
34  91  57   3
31  30   9  76
0   46  80  52
44  54  52  10
27  76  77   7
33  50   8  29
5   29  22  22
29  55   6  80
11  73   4  13
36   2  87  37
1   50  35  45
21   1  82  59
2   47   8  17
43  50  82  47
35  26  48  54
23  84  17  51
40   8   7  99
10  66  29  25
22  47  61  35
18  75  83  50
49  99   0  48
20  66  82  76
7   21  17  93
42  25  50  19
14   1  50  24
28  69  12  67
38  84  91  30